## Cropping & Resizing Detected Braces

##### System Installation

In [ ]:
!pip install -r https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt
!gdown https://drive.google.com/u/0/uc?id=1cdSf3NLweas03-_bQEafB3MlBrHpaBaL

In [2]:
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt') 

Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
Fusing layers... 
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 232 layers, 7246518 parameters, 0 gradients
Adding AutoShape... 
YOLOv5 🚀 2021-7-4 torch 1.9.0+cu102 CPU



In [53]:
results = model('/content/images/3424656-DSC06162.JPG')
labels, cord_thres = results.xyxyn[0][:, -1].numpy(), results.xyxyn[0][:, :-1].numpy()
labels, cord_thres

(array([          0,           0,           0], dtype=float32),
 array([[    0.21469,     0.47219,     0.27275,     0.59298,      0.9172],
        [    0.46366,     0.44526,     0.50524,      0.5265,     0.87682],
        [    0.62569,     0.65001,     0.65606,     0.70905,     0.73778]], dtype=float32))

In [54]:
for i in range(len(cord_thres)):
  print(cord_thres[i])

[    0.21469     0.47219     0.27275     0.59298      0.9172]
[    0.46366     0.44526     0.50524      0.5265     0.87682]
[    0.62569     0.65001     0.65606     0.70905     0.73778]


##### Required Images

In [1]:
from google.colab import drive
drive.mount('/content/ShardDrives/')

Mounted at /content/ShardDrives/


In [3]:
!mkdir images
!cp /content/ShardDrives/MyDrive/DataSet/Datasets/Set\ 1/* images/
!cp /content/ShardDrives/MyDrive/DataSet/Datasets/Set\ 2/* images/

mkdir: cannot create directory ‘images’: File exists


##### Processing Images

In [39]:
import os
import glob
import cv2 as cv
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt

!mkdir CroppedImages

In [ ]:
img = cv2.imread('/home/img/python.png', cv2.IMREAD_UNCHANGED)
resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
cv2.imwrite("IMAGE_NAME.png", warpedimage)

In [20]:
images = sorted(glob.glob("images/*"))
cv.imread(images[0],cv.COLOR_BGR2RGB).shape[0]

5304

In [55]:
images, i = sorted(glob.glob("images/*")), 0
for img in tqdm(images):
  results = model(img)
  labels, cord_thres = results.xyxyn[0][:, -1].numpy(), results.xyxyn[0][:, :-1].numpy()
  imx = cv.imread(img,cv.COLOR_BGR2RGB)
  Y, X = imx.shape[0], imx.shape[1]
  for o in range(len(cord_thres)):
    x, y, w, h = int((cord_thres[o][0])*X), int((cord_thres[o][1])*Y), int((cord_thres[o][2])*X), int((cord_thres[o][3])*Y)
    roi = imx[y:h, x:w]
    cv.imwrite('CroppedImages/Img_'+str(i)+'.jpg', roi); i+=1

In [59]:
!zip -q CroppedImages.zip CroppedImages/*
!cp -r CroppedImages.zip /content/ShardDrives/MyDrive/DataSet/Datasets/
!cp -r CroppedImages /content/ShardDrives/MyDrive/DataSet/Datasets/CroppedObjects
!mv /content/ShardDrives/MyDrive/DataSet/Datasets/CroppedObjects/CroppedImages/* /content/ShardDrives/MyDrive/DataSet/Datasets/CroppedObjects

In [69]:
images, i = sorted(glob.glob("CroppedImages/*")), 0
for img in tqdm(images):
  imx = cv.imread(img,cv.COLOR_BGR2RGB)
  Y, X = imx.shape[0], imx.shape[1]
  resized = cv.resize(imx, (608,608), interpolation = cv.INTER_AREA)
  cv.imwrite('ResizedObjects/Img_'+str(i)+'.jpg', resized); i+=1

In [70]:
!zip -q ResizedObjects.zip ResizedObjects/*
!cp -r ResizedObjects.zip /content/ShardDrives/MyDrive/DataSet/Datasets/
!cp -r ResizedObjects /content/ShardDrives/MyDrive/DataSet/Datasets/

In [15]:
cv.destroyAllWindows()